name: Upload Files to S3
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - 'LICENSE'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: '24'
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/gha-${{ github.event.organization.id }}-${{ github.event.repository.id }}-test
          role-session-name: ${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          aws-region: ${{ vars.AWS_REGION }}
          output-credentials: true
          output-env-credentials: false
      - name: Install dependencies
        working-directory: ./.github/ci/newupload/
        run: npm install
      - name: Install Build dependencies
        run: npm install
      - name: Build Vite
        run: npm run build
      - name: Run Upload Script
        run: node ./.github/ci/newupload/index.mjs
        env:
          AWS_REGION: ${{vars.AWS_REGION}}
          AWS_DEFAULT_REGION: ${{vars.AWS_DEFAULT_REGION}}
          AWS_ACCOUNT_ID: ${{vars.AWS_ACCOUNT_ID}}
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.creds.outputs.aws-session-token }}
          S3_BUCKET_NAME: ${{vars.S3_BUCKET_NAME}}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ vars.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SITE_DOMAINS: ${{ vars.SITE_DOMAINS }}
          
